name = "Side Quest Society AutoUpdated"
author = "Noxedwin"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1e02c86e1951686dd22e6c872ed38376b56f1a5761da546e0a019d4c2947d0c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
