name = "Side Quest Society AutoUpdated"
author = "Noxedwin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1580cfdcbc1886be88d4b18c3068fafba8c6e6d1ec0420f47db473a43abcf117"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
