name = "Side Quest Society Forever Edition"
author = "Noxedwin"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41a8d2d0a71be27989b467dcd313ee6944654473ec1ba489bd9ebb0d9ca5c0e8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
