name = "Side Quest Society Forever Edition"
author = "Noxedwin"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "998783d7e62a0e3e716a6090d22024869936867d84633f34b81bd601d9e6dcc1"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
