name = "Side Quest Society Forever Edition"
author = "Noxedwin"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e193ccbca9060587a9bff1f5604d7944cecd48f16eef352a4a14ffaaf9706307"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
